import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Wine and Beer</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>
					Welcome to <a href="#">Wine and Beer</a>
				</h1>

				<p className={styles.description}>Which one do you want to drink on this 🎄christmas🎄</p>

				<div className={styles.grid}>
					<a href="wines" className={styles.card}>
						<h2>🍷 Drink Wine &rarr;</h2>
						<p>ed, White, Rose, Port, Sparkling, Dessert</p>
					</a>

					<a href="beers" className={styles.card}>
						<h2>🍺 Drink Beer &rarr;</h2>
						<p>Ale, Stout</p>
					</a>
				</div>
			</main>

			<footer className={styles.footer}></footer>
		</div>
	);
};

export default Home;
